### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by alercah** [james-j-obrien/bevy_vector_shapes#13]
I'm tentatively interested in using this library as a more powerful base for doing some diagrams, as a replacement for manim, but SVG export is a must-have for me.

**Comment by james-j-obrien** [comment]
SVG exports are outside the scope of the library as I currently see it. If you want to draw complex SVG based diagrams it's likely easier to draw them using a library that renders SVGs to ensure parity like femtovg.

While I imagine it's possible to map most of the API of this library to an output SVG there are features supported by the library that can't be trivially converted to an SVG (even ignoring the 3D aspect).

If you wanted to achieve this for your use case you could collect the entities that are part of your diagram and map them to an SVG yourself using a library like usvg, but it's not something I'm particularly interested in implementing/maintaining at this time.
