### ISSUE TITLE
Vectors disapear after 1 frame when trying to follow canvas examples

### ISSUE THREAD

**Issue by spooky-th-ghost** [james-j-obrien/bevy_vector_shapes#22]
Not a bug or a feature request really, I'm just having an issue getting the lib to work with a canvas, I can see my shape render for what appears to be one frame before it disapears:

```rust
use bevy::{prelude::*, render::texture::ImageSampler};
use bevy_inspector_egui::quick::WorldInspectorPlugin;
use bevy_vector_shapes::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(ShapePlugin::new(ShapeConfig {
            disable_laa: true,
            ..ShapeConfig::default_3d()
        }))
        .add_plugins(WorldInspectorPlugin::default())
        .insert_resource(ClearColor(Color::DARK_GRAY))
        .insert_resource(Msaa::Off)
        .add_systems(Startup, setup)
        .add_systems(Update, draw)
        .run();
}

fn setup(mut commands: Commands, mut images: ResMut<Assets<Image>>) {
    let mut config = CanvasConfig::new(256, 256);
    config.sampler = ImageSampler::nearest();
    commands.spawn_canvas(images.as_mut(), config);

    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(0., 0., 16.).looking_at(Vec3::ZERO, Vec3::Y),
        ..default()
    });
}

fn draw(mut painter: ShapePainter, canvas_query: Query<(Entity, &Canvas)>) {
    let (canvas_e, canvas) = canvas_query.single();

    painter.image(canvas.image.clone(), Vec2::splat(20.));
    painter.set_canvas(canvas_e);
    painter.set_scale(Vec3::ONE * 48.0);
    painter.color = Color::MIDNIGHT_BLUE;
    painter.circle(0.5);
    painter.line(Vec3::new(-5.0, 0.0, 0.0), Vec3::new(5.0, 0.0, 0.0));
}
```

I'm wondering if there is a crucial step I'm missing from the example, but I haven't been able to find the issue yet

**Comment by james-j-obrien** [comment]
Ah so this took me a minute to notice so I don't blame you for missing it: You set the canvas on the first call to `draw` and since you don't reset the painter on the next run of `draw` the canvas is already set and the image get's drawn to the canvas instead so you can't see it anymore. Adding `painter.reset()` at the end of the function should solve it for you.

I don't like how much of a footgun this is, I would prefer there were some way for me to automatically reset the painter between system runs to avoid confusion. I can think of some hacky ways to enable that but I will also consider making a change upstream in bevy to enable a better experience here.

Hope this helps :)

**Comment by spooky-th-ghost** [comment]
that was it, thank so much! would it be too overzealous to just reset the painter in a late update system?

**Comment by james-j-obrien** [comment]
The complication is that the state for the shape config is stored in a `Local` not in a way that is queryable by a hypothetical `reset_painters` system. I would need to store the configs in the ECS somewhere so I can reset it in a system or have a way to take a copy of the value stored in the global resource on each system invocation. If there was some mechanism for a `SystemParam` to define a function that runs on system invocation that would work.

In a world where `bevy_ecs` was more advanced and we had systems stored as entities we could theoretically query for the locals to reset them but we are a ways away from that being possible.

**Comment by spooky-th-ghost** [comment]
ahhh that makes sense, either way really great lib, I'm planning on using it pretty heavily for a project I'm working on so I'll be keeping an eye out/looking for ways to contribute, keep up the awesome work!
