### ISSUE TITLE
Possible to create a transparent canvas?

### ISSUE THREAD

**Issue by spooky-th-ghost** [james-j-obrien/bevy_vector_shapes#23]
I'm trying to figure out a way to use vector shapes for a heads up display, I've poking around the last few days and I'm wondering if there is a way have the canvas render as transparent

**Comment by james-j-obrien** [comment]
I have admittedly never tested this but you should be able to set the painter color to a transparent white and it will apply that transparency to a textured shape. 

Note that the `.image` helper function (which is a wrapper around `.rect`) sets the color to opaque white (to prevent users from accidentally tinting their images when they don't intend to) so you will have to either use `.rect` directly or create your own helper.

**Comment by spooky-th-ghost** [comment]
thanks! I actually ended up just setting a transparent clear color on the config and that looks to be working for me!
