### ISSUE TITLE
At certain perspectives, shapes seem to Z-sort incorrectly

### ISSUE THREAD

**Issue by Seldom-SE** [james-j-obrien/bevy_vector_shapes#46]
I'm making a health bar for enemies in a 3D game. There's a black background rectangle and a red rectangle that represents the health, so I draw the former physically behind the latter. However, when the camera and the health bar are are in certain positions, the background may appear in front of the health. Here's a very minimal repro:

```rust
use bevy::prelude::*;
use bevy_vector_shapes::prelude::*;

pub fn main() {
    App::new()
        .add_plugins((DefaultPlugins, ShapePlugin::default()))
        .add_systems(Startup, init)
        .add_systems(Update, draw_shapes)
        .run();
}

const CAM_POS: Vec3 = Vec3::new(0., 70., -10.);
const BACKGROUND_POS: Vec3 = Vec3::new(0., 0., 10.);

fn init(mut cmds: Commands) {
    cmds.spawn(Camera3dBundle {
        transform: Transform::from_translation(CAM_POS).looking_at(BACKGROUND_POS, Dir3::Y),
        ..default()
    });
}

fn draw_shapes(mut painter: ShapePainter) {
    painter.set_3d();

    painter.color = Color::BLACK;
    // Look away from the camera so positive X is to the right
    painter.transform =
        Transform::from_translation(BACKGROUND_POS).looking_to(BACKGROUND_POS - CAM_POS, Dir3::Y);

    let width = 10.;
    let height = 1.;

    // Background
    painter.rect(Vec2::new(width, height));

    // Health
    painter.color = Srgba::RED.into();
    painter.set_translation((CAM_POS + BACKGROUND_POS) / 2.);
    painter.rect(Vec2::new(width, height));
}
```

Here's it is in a repo: https://github.com/Seldom-SE/testetst/blob/c24ae75c330862b8ed59b7b0728b38e1daf34075/src/main.rs. Here, the health is at the midpoint between the camera and the background, but the background shows in front of it:

![image](https://github.com/user-attachments/assets/462e3f54-7438-4831-b0e6-fb05aec1485d)

There's some tweaks that can be made that would fix this (ex make the bar face toward the camera instead of away from it, draw the background and health at the same position, etc), but they don't fix the issue for all perspectives. I have another repro that demonstrates the issue with a variety of perspectives: https://github.com/Seldom-SE/testetst/blob/22d5a81dcddfb6dab424c7141dafde0855db1557/src/main.rs. That should be more useful in narrowing down the issue.

**Comment by Seldom-SE** [comment]
Here's a video of the second repro

https://github.com/user-attachments/assets/e32c5414-d306-4b79-b308-a557525bfbfc

and here's my `AdapterInfo`

```
2024-09-05T19:17:51.020898Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 570 Series (RADV POLARIS10)", vendor: 4098, device: 26591, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.2.1-arch1.1", backend: Vulkan }
```

**Comment by Seldom-SE** [comment]
Here's a screenshot from our actual game. I made the health bars really big to test something unrelated and I noticed that these meshes are being silhouetted with the health color when the background shows in front of the health

![image](https://github.com/user-attachments/assets/f508fd46-1cbe-424f-bf54-7d4f4c9de66b)

**Comment by james-j-obrien** [comment]
It seems this issue was introduced in this PR: #40 
In order to mitigate you can fork and in `render_3d.rs` replace:
```rust
let dist_point = data.transform().transform_vector3(instance.origin);
let distance = rangefinder.distance_translation(&dist_point);
```
with:
```rust
let distance = rangefinder.distance(&data.transform())
```

I will work on a more appropriate fix in the short term so no-one else gets affected by this.

**Comment by james-j-obrien** [comment]
Ok, pushed a fix, should be available as 0.8.2

**Comment by Seldom-SE** [comment]
Thank you!

**Comment by Occuros** [comment]
With the latest version of bevy `0.16` I experience the same, where lines are drawn on top of a shape which is in 3d above.

It change based on the camera perspective, might something have changed in bevy's renderer?
