### ISSUE TITLE
Alignment between two shapes when using Alignment::Billboard

### ISSUE THREAD

**Issue by nylira** [james-j-obrien/bevy_vector_shapes#8]
Hi there, not sure if this is classified as a bug or if I just need some advice on how to design this. I have a health bar component that I want rendered as two rectanges. A foreground rectangle that has the entity's current health, and a background black rectangle.

With this code I get what I am asking for:

![Screenshot from 2023-05-01 23-32-54](https://user-images.githubusercontent.com/172531/235478792-c8a45cc6-e6fc-4c4c-a6bc-ddae1c1e9af7.png)

```rust
pub fn draw_health_bars(
    mut painter: ShapePainter,
    mut q_child: Query<&Parent, With<BarHealth>>,
    q_parent: Query<(&Health, &Transform)>,
) {
    for parent in q_child.iter_mut() {
        let (health, transform) = q_parent.get(parent.get()).unwrap();
        let health_pct = health.value as f32 / health.max as f32;
        let tl = transform.translation;

        painter.alignment = Alignment::Billboard;

        // paint healthbar bg
        painter.transform.translation = Vec3::new(tl.x, tl.y + 0.5, tl.z);
        painter.color = Color::BLACK;
        painter.rect(Vec2::new(1.0, 0.1));

        // paint healthbar value
        //painter.transform.translation += Vec3::X * (1.0 - health_pct) / 2.0;
        painter.color = Color::GREEN * health_pct + Color::RED * (1. - health_pct);
        painter.rect(Vec2::new(1.0 * health_pct, 0.1));
    }
}
```

But the issue is that the rectanges are horizontally aligned to the center of the parent component. I would like the health bar (the foreground yellow rectangle) to be horizontally aligned to the left. If I uncomment the `painter.transform.translation` line and run the application, the bars are no longer aligned on top of each other:

![Screenshot from 2023-05-01 23-35-17](https://user-images.githubusercontent.com/172531/235479153-94f37ba0-445a-4ec0-8cd7-59ef847566b7.png)

Which I am assuming is because of the `Alignment::Billboard` setting that I have enabled. Any thoughts on how to tackle this?

**Comment by james-j-obrien** [comment]
This is in essence working as intended. Since the rectangles billboard around their center, once they are offset they billboard around different points and misalign themselves. The easiest way to get around this is to render all your shapes as children of some other entity and then manually turn that entity to face the camera. That way all the children shapes will stay well positioned relative to one another.

That might look something like this:
```rust
commands
    .spawn((BillboardParent, SpatialBundle::default()))
    // with_shape_children allows inserting a config for drawing shapes even as children of non-shape entities
    .with_shape_children(painter.config(), |child_painter| {
        // Draw the shapes you want to be children here
        // Translation and rotation should all work as expected and be done relative to the parent
        child_painter.rect(Vec2::new(1.0, 1.0));
    });

// Some system that rotates the parent to face the camera
fn apply_billboarding(mut billboards: Query<&mut Transform, With<BillboardParent>>, mut camera: Query<&Transform, With<Camera>>) {
    // ...
}
```

Note you will have to use v0.3.4 for this as it is the earliest version that exposes the trait for ```with_shape_children```. You can then leave out setting the Alignment at all.

**Comment by nylira** [comment]
Appreciate the pointer. I can definitely work with this. Thanks!
